# Generated by Django 4.2.3 on 2023-08-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
